services:
  - type: web
    name: splitwise-clone
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DB_URI
        sync: false
      - key: MAIL_USER
        sync: false
      - key: MAIL_PASS
        sync: false
